Feature: `finalFragment` flag for WebSocketFrame
dream11/zio-http pull request #393
Opened 2021-10-12 12:02 UTC by morozov11

On Gprs/LTE connections often need continuation frames processing, but current version zio-http don't contains finalization flag for continuation messages.

2021-10-12 14:46 UTC, tusharmath commented
Can you expand more on why you would require `finalFragment`

2021-10-13 07:43 UTC, morozov11 commented
> Can you expand more on why you would require `finalFragment`

In iOS 15 for Safai, an experimental function was enabled by default: nsurlsession websocket, which is why, when connecting via LTE, large ws frames begin to split with Continuation. Ideally, you need a facade to assemble a large package into one. But for now, just a flag would be enough.

2021-10-14 13:28 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
> +  val finalFragment: Boolean            = true
```suggestion
  def isFinal: Boolean
```

2021-10-14 13:33 UTC, tusharmath commented on example/src/main/scala/WebSocketAdvanced.scala
> +  private val echo = Socket.collect[WebSocketFrame] { case WebSocketFrame.Text(text, _) =>
Instead of deploying a breaking change like this I would prefer if we could access the `isFinal` flag using a accessor eg:

```scala
Socket.collect[WebSocketFrame] { case fr @ Text(text) => fr.isFinal }
```

2021-10-14 16:25 UTC, morozov11 commented on example/src/main/scala/WebSocketAdvanced.scala
> +  private val echo = Socket.collect[WebSocketFrame] { case WebSocketFrame.Text(text, _) =>
ок

2021-10-15 02:39 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
> +  def isFinal: Boolean                  = true
```suggestion
  def isFinal: Boolean
```

2021-10-15 03:46 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
>    final case class Close(status: Int, reason: Option[String]) extends WebSocketFrame
Close, Ping, Pong should all have `isFinal` implemented isn't it?

2021-10-15 07:29 UTC, morozov11 commented on zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
>    final case class Close(status: Int, reason: Option[String]) extends WebSocketFrame
WebSocketFrame trait has isFinal = true by default. For Close, Ping, Pong there will be no Continuation frames. I think there is no point in setting this value manually. Right?

2021-10-15 07:42 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
> +  def isFinal: Boolean
```suggestion
  def toWebSocketFrame: JWebSocketFrame = WebSocketFrame.toJFrame(self)
  def isFinal: Boolean                  = true
```

2021-10-15 07:42 UTC, tusharmath commented on zio-http/src/main/scala/zhttp/socket/WebSocketFrame.scala
>    def toWebSocketFrame: JWebSocketFrame = WebSocketFrame.toJFrame(self)
```suggestion
  final def toWebSocketFrame: JWebSocketFrame = WebSocketFrame.toJFrame(self)
```

2021-10-15 07:46 UTC, tusharmath approved these changes

2021-10-15 07:50 UTC, tusharmath requested changes
Can you run `fmt` command once.

2021-10-15 10:19 UTC, morozov11 commented
> Can you run `fmt` command once.

I ran `fmt` command, but no changes happened and nothing added to commit. Locally the `sbt ++2.13.6 fmtCheck` executed fine. I don't understand what i am doing wrong.

2021-10-20 08:24 UTC, amitksingh1490 commented
> > Can you run `fmt` command once.
> 
> I ran `fmt` command, but no changes happened and nothing added to commit. Locally the `sbt ++2.13.6 fmtCheck` executed fine. I don't understand what i am doing wrong. May be incorrect line endings?

Now the formatting is fixed could you please update the examples `WebSocketEcho.scala` and `WebSocketAdvanced.scala`

2021-10-26 16:39 UTC, tusharmath approved these changes

2021-10-26 16:39 UTC, merged