Update sbt to 1.5.0-RC1
dream11/zio-http pull request #58
Opened 2021-03-19 09:15 UTC by sh0hei

2021-03-19 09:19 UTC, sh0hei commented on build.sbt
> +    publish / skip := true,
cf. https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash

2021-03-19 14:19 UTC, tusharmath requested changes

2021-03-19 14:19 UTC, tusharmath commented on project/build.properties
> +sbt.version=1.5.0-RC1
Not sure if we should update the version already. The changes can be incorporated though.

2021-04-05 13:34 UTC, tusharmath commented
Closing in favour of #119

2021-04-05 13:34 UTC, closed without merging